
# Nice colors inside tmux
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setb24=\E[48:2::%p1%{65536}%/%d:%p1%{256}%/%d&255%:%p1%&255%m'

# Change prefix to Ctrl-Space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Status bar
set -g status-position top

# Sensible
set -s escape-time 0
set -g history-limit 10000
set -g display-time 4000
set -g status-interval 5

# Reload config
bind r source-file $HOME/.tmux.conf

#### revisit below

setw -g mode-keys vi
setw -g status-keys vi

# Don't wrap back around when searching
setw -g wrap-search off

# enable window titles
set -g set-titles on

bind k copy-mode \; send-keys k 0
bind C-u copy-mode -u \; send-keys 0

bind P swap-window -t -1\; select-window -t -1
bind N swap-window -t +1\; select-window -t +1
